name: Build and Deploy to AWS Fargate Spot

on:
  push:
    branches:
      - main  # Deploys when code is pushed to the main branch
      - release
env:
  AWS_REGION: ap-northeast-1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      #   with:
      #     aws-region: ${{ env.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

      # Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build . -t chatgpt-proxy:$IMAGE_TAG
          echo "::set-output name=image::$IMAGE_TAG"
          
      - name: Push the Docker Image to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: docker push my-image:$GITHUB_SHA
